/**
 * Comprehensive List of 50 Indian Cities mapped to State & Default PIN Code
 */
export const INDIAN_CITIES = [
  { name: 'Delhi', state: 'Delhi', pincode: '110001' },
  { name: 'New Delhi', state: 'Delhi', pincode: '110003' },
  { name: 'Noida', state: 'Uttar Pradesh', pincode: '201301' },
  { name: 'Ghaziabad', state: 'Uttar Pradesh', pincode: '201001' },
  { name: 'Gurugram', state: 'Haryana', pincode: '122001' },
  { name: 'Faridabad', state: 'Haryana', pincode: '121001' },
  { name: 'Lucknow', state: 'Uttar Pradesh', pincode: '226001' },
  { name: 'Kanpur', state: 'Uttar Pradesh', pincode: '208001' },
  { name: 'Prayagraj', state: 'Uttar Pradesh', pincode: '211001' },
  { name: 'Varanasi', state: 'Uttar Pradesh', pincode: '221001' },
  { name: 'Agra', state: 'Uttar Pradesh', pincode: '282001' },
  { name: 'Jaipur', state: 'Rajasthan', pincode: '302001' },
  { name: 'Jodhpur', state: 'Rajasthan', pincode: '342001' },
  { name: 'Udaipur', state: 'Rajasthan', pincode: '313001' },
  { name: 'Mumbai', state: 'Maharashtra', pincode: '400001' },
  { name: 'Pune', state: 'Maharashtra', pincode: '411001' },
  { name: 'Nagpur', state: 'Maharashtra', pincode: '440001' },
  { name: 'Nashik', state: 'Maharashtra', pincode: '422001' },
  { name: 'Ahmedabad', state: 'Gujarat', pincode: '380001' },
  { name: 'Surat', state: 'Gujarat', pincode: '395001' },
  { name: 'Vadodara', state: 'Gujarat', pincode: '390001' },
  { name: 'Indore', state: 'Madhya Pradesh', pincode: '452001' },
  { name: 'Bhopal', state: 'Madhya Pradesh', pincode: '462001' },
  { name: 'Raipur', state: 'Chhattisgarh', pincode: '492001' },
  { name: 'Patna', state: 'Bihar', pincode: '800001' },
  { name: 'Ranchi', state: 'Jharkhand', pincode: '834001' },
  { name: 'Kolkata', state: 'West Bengal', pincode: '700001' },
  { name: 'Siliguri', state: 'West Bengal', pincode: '734001' },
  { name: 'Bhubaneswar', state: 'Odisha', pincode: '751001' },
  { name: 'Cuttack', state: 'Odisha', pincode: '753001' },
  { name: 'Hyderabad', state: 'Telangana', pincode: '500001' },
  { name: 'Warangal', state: 'Telangana', pincode: '506001' },
  { name: 'Bengaluru', state: 'Karnataka', pincode: '560001' },
  { name: 'Mysuru', state: 'Karnataka', pincode: '570001' },
  { name: 'Mangaluru', state: 'Karnataka', pincode: '575001' },
  { name: 'Chennai', state: 'Tamil Nadu', pincode: '600001' },
  { name: 'Coimbatore', state: 'Tamil Nadu', pincode: '641001' },
  { name: 'Madurai', state: 'Tamil Nadu', pincode: '625001' },
  { name: 'Kochi', state: 'Kerala', pincode: '682001' },
  { name: 'Thiruvananthapuram', state: 'Kerala', pincode: '695001' },
  { name: 'Visakhapatnam', state: 'Andhra Pradesh', pincode: '530001' },
  { name: 'Vijayawada', state: 'Andhra Pradesh', pincode: '520001' },
  { name: 'Chandigarh', state: 'Punjab', pincode: '160001' },
  { name: 'Amritsar', state: 'Punjab', pincode: '143001' },
  { name: 'Ludhiana', state: 'Punjab', pincode: '141001' },
  { name: 'Guwahati', state: 'Assam', pincode: '781001' },
  { name: 'Shimla', state: 'Himachal Pradesh', pincode: '171001' },
  { name: 'Dehradun', state: 'Uttarakhand', pincode: '248001' },
  { name: 'Jammu', state: 'Jammu and Kashmir', pincode: '180001' },
  { name: 'Srinagar', state: 'Jammu and Kashmir', pincode: '190001' },
]
