import LegalService from '../models/legalService.model.js';

const sampleLegalServices = [
  // ─── 1. NATIONAL HELPLINES ──────────────────────────────────────────────────
  {
    name: 'National Emergency Helpline (112)',
    type: 'Helpline',
    category: 'Criminal Law',
    description: 'Single emergency number in India for immediate police, medical, and fire assistance under ERSS.',
    address: 'Ministry of Home Affairs, North Block',
    city: 'New Delhi',
    state: 'Delhi',
    phone: '112',
    email: 'erss@mha.gov.in',
    website: 'https://erss.in',
    workingHours: '24/7 Toll-Free Emergency',
    verified: true,
    latitude: 28.6143,
    longitude: 77.2088,
  },
  {
    name: 'National Women Helpline (181)',
    type: 'Helpline',
    category: 'Women Safety',
    description: '24-hour toll-free helpline providing immediate response, counseling, and legal aid referral for women affected by violence.',
    address: 'Ministry of Women and Child Development, Shastri Bhawan',
    city: 'New Delhi',
    state: 'Delhi',
    phone: '181',
    email: 'wcd@nic.in',
    website: 'https://wcd.nic.in',
    workingHours: '24/7 Toll-Free Helpline',
    verified: true,
    latitude: 28.6189,
    longitude: 77.2155,
  },
  {
    name: 'National Cyber Crime Helpline (1930)',
    type: 'Helpline',
    category: 'Cyber Crime',
    description: 'Official helpline for reporting financial fraud, cyber stalking, identity theft, and online harassment under I4C.',
    address: 'Indian Cyber Crime Coordination Centre (I4C), MHA',
    city: 'New Delhi',
    state: 'Delhi',
    phone: '1930',
    email: 'cybercrime-help@gov.in',
    website: 'https://cybercrime.gov.in',
    workingHours: '24/7 Toll-Free Helpline',
    verified: true,
    latitude: 28.6139,
    longitude: 77.209,
  },
  {
    name: 'National Childline (1098)',
    type: 'Helpline',
    category: 'Child Protection',
    description: 'Emergency phone outreach service for children in need of care and legal protection under POCSO and JJ Act.',
    address: 'Childline India Foundation, Mumbai',
    city: 'Mumbai',
    state: 'Maharashtra',
    phone: '1098',
    email: 'dial1098@childlineindia.org.in',
    website: 'https://www.childlineindia.org.in',
    workingHours: '24/7 Toll-Free Emergency',
    verified: true,
    latitude: 19.076,
    longitude: 72.8777,
  },
  {
    name: 'National Consumer Helpline (1915)',
    type: 'Helpline',
    category: 'Consumer Law',
    description: 'Official Ministry of Consumer Affairs portal for filing consumer complaints against unfair trade practices and defective goods.',
    address: 'Department of Consumer Affairs, Krishi Bhawan',
    city: 'New Delhi',
    state: 'Delhi',
    phone: '1915',
    email: 'consumer-helpline@nic.in',
    website: 'https://consumerhelpline.gov.in',
    workingHours: '8:00 AM - 8:00 PM (Mon-Sat)',
    verified: true,
    latitude: 28.6175,
    longitude: 77.212,
  },

  // ─── 2. GOVERNMENT LEGAL AID & DLSAS ───────────────────────────────────────
  {
    name: 'National Legal Services Authority (NALSA)',
    type: 'Government Legal Aid',
    category: 'Criminal Law',
    description: 'Statutory body constituted under the Legal Services Authorities Act, 1987 to provide free legal services to eligible citizens.',
    address: '11, Jamnagar House, Shahjahan Road',
    city: 'New Delhi',
    state: 'Delhi',
    phone: '011-23386176',
    email: 'nalsa-dla@nic.in',
    website: 'https://nalsa.gov.in',
    workingHours: '9:30 AM - 5:30 PM (Mon-Fri)',
    verified: true,
    latitude: 28.6085,
    longitude: 77.2245,
  },
  {
    name: 'District Legal Services Authority (DLSA) - Central Delhi',
    type: 'DLSA',
    category: 'Family Law',
    description: 'District court legal aid cell providing free advocates, mediation, and Lok Adalat resolution for weaker sections.',
    address: 'Room No. 23, Tis Hazari Courts Complex',
    city: 'New Delhi',
    state: 'Delhi',
    phone: '011-23968015',
    email: 'dlsa-central@nic.in',
    website: 'https://delhiservices.gov.in/dlsa',
    workingHours: '10:00 AM - 5:00 PM (Mon-Sat)',
    verified: true,
    latitude: 28.6667,
    longitude: 77.2167,
  },
  {
    name: 'District Legal Services Authority (DLSA) - Mumbai Suburban',
    type: 'DLSA',
    category: 'Property Law',
    description: 'Free legal advice and representation for senior citizens, SC/ST, women, and victims of crime in Mumbai district.',
    address: 'City Civil & Sessions Court, Fort',
    city: 'Mumbai',
    state: 'Maharashtra',
    phone: '022-22673255',
    email: 'dlsa.mumbai@maharashtra.gov.in',
    website: 'https://legalaid.maharashtra.gov.in',
    workingHours: '10:00 AM - 5:00 PM (Mon-Sat)',
    verified: true,
    latitude: 18.9298,
    longitude: 72.8333,
  },
  {
    name: 'District Legal Services Authority (DLSA) - Bengaluru Urban',
    type: 'DLSA',
    category: 'Employment',
    description: 'Karnataka State Legal Services Authority unit for labor disputes, tenant legal defense, and free legal aid.',
    address: 'Nyayadegula, H. Siddaiah Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    phone: '080-22223846',
    email: 'kslsa@kar.nic.in',
    website: 'https://kslsa.kar.nic.in',
    workingHours: '10:00 AM - 5:30 PM (Mon-Sat)',
    verified: true,
    latitude: 12.96,
    longitude: 77.58,
  },

  // ─── 3. LEGAL NGOs ──────────────────────────────────────────────────────────
  {
    name: 'Bachpan Bachao Andolan (BBA)',
    type: 'NGO',
    category: 'Child Protection',
    description: 'Pioneering child rights NGO founded by Nobel Laureate Kailash Satyarthi, fighting child labor and trafficking legally.',
    address: 'L-6, Kalkaji',
    city: 'New Delhi',
    state: 'Delhi',
    phone: '011-49275700',
    email: 'info@bba.org.in',
    website: 'https://bba.org.in',
    workingHours: '9:30 AM - 6:00 PM (Mon-Sat)',
    verified: true,
    latitude: 28.5422,
    longitude: 77.2588,
  },
  {
    name: 'Lawyers Collective',
    type: 'NGO',
    category: 'Women Safety',
    description: 'Non-profit organization advocating for women rights, domestic violence protection (PWDVA), and healthcare rights in India.',
    address: 'Jangpura Extension',
    city: 'New Delhi',
    state: 'Delhi',
    phone: '011-24377101',
    email: 'wri@lawyerscollective.org',
    website: 'https://www.lawyerscollective.org',
    workingHours: '10:00 AM - 6:00 PM (Mon-Fri)',
    verified: true,
    latitude: 28.58,
    longitude: 77.24,
  },

  // ─── 4. VERIFIED ADVOCATES (SAMPLE DATA) ──────────────────────────────────
  {
    name: 'Adv. Meenakshi Sharma (Senior Advocate)',
    type: 'Verified Advocate',
    category: 'Family Law',
    description: 'Specialist in matrimonial disputes, custody cases, mutual consent divorce, and domestic violence representation in Delhi High Court.',
    address: 'Chamber 412, Lawyers Block, Saket District Court',
    city: 'New Delhi',
    state: 'Delhi',
    phone: '+91-9810123456',
    email: 'adv.sharma@delhi-bar.in',
    website: 'https://meenakshisharma-adv.in',
    workingHours: '4:00 PM - 8:00 PM (Mon-Sat)',
    verified: true,
    latitude: 28.528,
    longitude: 77.218,
  },
  {
    name: 'Adv. Rajeshwar Rao & Associates',
    type: 'Verified Advocate',
    category: 'Property Law',
    description: 'Expertise in real estate title verification, RERA buyer complaints, partition suits, and land acquisition legal audits.',
    address: 'Suite 204, High Court Chambers, MG Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    phone: '+91-9845098765',
    email: 'rao.legal@bengaluru-bar.org',
    website: 'https://raolegal.in',
    workingHours: '10:00 AM - 7:00 PM (Mon-Sat)',
    verified: true,
    latitude: 12.975,
    longitude: 77.605,
  },
  {
    name: 'Adv. Vikramaditya Deshmukh',
    type: 'Verified Advocate',
    category: 'Cyber Crime',
    description: 'Cyber law consultant specializing in IT Act 2000 violations, data breach compliance, financial fraud defense, and DPDP advisory.',
    address: 'Maker Chambers VI, Nariman Point',
    city: 'Mumbai',
    state: 'Maharashtra',
    phone: '+91-9820034567',
    email: 'v.deshmukh@cyberlaw-mumbai.com',
    website: 'https://cyberlawdeshmukh.com',
    workingHours: '10:00 AM - 6:30 PM (Mon-Fri)',
    verified: true,
    latitude: 18.925,
    longitude: 72.822,
  },
  {
    name: 'Adv. Ananya Roy',
    type: 'Verified Advocate',
    category: 'Consumer Law',
    description: 'Advocate handling consumer forum complaints, insurance claim rejections, flight cancellation refunds, and builder penalty notices.',
    address: 'City Civil Court Chambers, Park Street',
    city: 'Kolkata',
    state: 'West Bengal',
    phone: '+91-9830011223',
    email: 'ananya.roy@kolkatabar.org',
    website: 'https://royconsumerlegal.in',
    workingHours: '11:00 AM - 6:00 PM (Mon-Sat)',
    verified: true,
    latitude: 22.55,
    longitude: 88.35,
  },
];

export const seedLegalServices = async () => {
  try {
    const count = await LegalService.countDocuments();
    if (count === 0) {
      await LegalService.insertMany(sampleLegalServices);
      console.log(`🌱 Successfully seeded ${sampleLegalServices.length} Legal Services & Helplines into database!`);
    }
  } catch (error) {
    console.error('Failed to seed Legal Services:', error.message);
  }
};
