import { useState } from 'react'
import { motion } from 'framer-motion'
import { FileCheck2, Search, Trash2, Download } from 'lucide-react'
import toast from 'react-hot-toast'

const MOCK_REPORTS = [
  { id: 'rep_1', title: 'Rent Agreement Executive Legal Report', docName: 'Rent_Agreement_Noida.pdf', generatedOn: '2025-07-20', riskScore: 'Low Risk' },
  { id: 'rep_2', title: 'Consumer Notice Statutory Audit Report', docName: 'Consumer_Forum_Notice.pdf', generatedOn: '2025-07-18', riskScore: 'Medium Risk' },
  { id: 'rep_3', title: 'Employment Agreement Risk Assessment', docName: 'TechCorp_Agreement.pdf', generatedOn: '2025-07-15', riskScore: 'Low Risk' },
]

export default function AdminReports() {
  const [reports, setReports] = useState(MOCK_REPORTS)

  const handleDelete = (id) => {
    if (!window.confirm('Delete report?')) return
    setReports((prev) => prev.filter((r) => r.id !== id))
    toast.success('Report record deleted.')
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      className="space-y-6 max-w-7xl mx-auto pb-12"
    >
      <div className="border-b border-slate-200 pb-5">
        <h1 className="text-2xl font-extrabold text-slate-900">Generated Reports Audit</h1>
        <p className="text-xs text-slate-500 mt-1">Review all PDF and JSON executive reports generated by the platform.</p>
      </div>

      <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-xs overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="border-b border-slate-200 bg-slate-50 text-slate-500 uppercase font-semibold">
                <th className="p-3">Report Title</th>
                <th className="p-3">Source Document</th>
                <th className="p-3">Generated On</th>
                <th className="p-3">Risk Assessment</th>
                <th className="p-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 font-medium text-slate-800">
              {reports.map((r) => (
                <tr key={r.id} className="hover:bg-slate-50/80 transition-colors">
                  <td className="p-3 font-bold text-indigo-900">{r.title}</td>
                  <td className="p-3">{r.docName}</td>
                  <td className="p-3 font-mono">{r.generatedOn}</td>
                  <td className="p-3 font-bold text-emerald-700">{r.riskScore}</td>
                  <td className="p-3 text-right">
                    <button onClick={() => handleDelete(r.id)} className="p-1.5 text-slate-400 hover:text-red-600">
                      <Trash2 size={15} />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </motion.div>
  )
}
