import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { Trash2 } from 'lucide-react'
import { reportsAPI } from '../../services/api'
import toast from 'react-hot-toast'

export default function AdminReports() {
  const [reports, setReports] = useState([])
  const [loading, setLoading] = useState(true)

  const fetchReports = async () => {
    setLoading(true)
    try {
      const res = await reportsAPI.getReports()
      const list = res.data?.data?.reports || []
      setReports(list)
    } catch (err) {
      toast.error('Failed to load generated reports from server.')
      setReports([])
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchReports()
  }, [])

  const handleDelete = async (id) => {
    if (!window.confirm('Are you sure you want to delete this executive report?')) return
    try {
      await reportsAPI.deleteReport(id)
      setReports((prev) => prev.filter((r) => (r._id || r.id) !== id))
      toast.success('Report record deleted successfully.')
    } catch (err) {
      toast.error(err.message || 'Failed to delete report.')
    }
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      className="space-y-6 max-w-7xl mx-auto pb-12"
    >
      <div className="border-b border-slate-200 pb-5">
        <h1 className="text-2xl font-extrabold text-slate-900">Generated Reports Audit</h1>
        <p className="text-xs text-slate-500 mt-1">Review all PDF executive reports generated by platform users.</p>
      </div>

      <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-xs overflow-hidden">
        {loading ? (
          <div className="flex h-48 items-center justify-center">
            <div className="h-8 w-8 animate-spin rounded-full border-4 border-indigo-600 border-t-transparent" />
          </div>
        ) : reports.length === 0 ? (
          <div className="p-8 text-center text-xs text-slate-500 font-medium">
            No generated reports found.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead>
                <tr className="border-b border-slate-200 bg-slate-50 text-slate-500 uppercase font-semibold">
                  <th className="p-3">Report Title</th>
                  <th className="p-3">Source Document</th>
                  <th className="p-3">Generated On</th>
                  <th className="p-3">Format</th>
                  <th className="p-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 font-medium text-slate-800">
                {reports.map((r) => {
                  const id = r._id || r.id
                  const title = r.title || 'Legal Analysis Report'
                  const docTitle = r.documentTitle || r.documentId?.title || 'Document'
                  const dateStr = new Date(r.createdAt || Date.now()).toLocaleDateString('en-IN')

                  return (
                    <tr key={id} className="hover:bg-slate-50/80 transition-colors">
                      <td className="p-3 font-bold text-indigo-900">{title}</td>
                      <td className="p-3">{docTitle}</td>
                      <td className="p-3 font-mono">{dateStr}</td>
                      <td className="p-3 font-bold text-indigo-600 uppercase">{r.format || 'PDF'}</td>
                      <td className="p-3 text-right">
                        <button
                          onClick={() => handleDelete(id)}
                          className="p-1.5 text-slate-400 hover:text-red-600 transition-colors cursor-pointer"
                          title="Delete Report"
                        >
                          <Trash2 size={15} />
                        </button>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </motion.div>
  )
}
